#!/usr/bin/env python3
#
# Copyright (c) 2106, Al Stone <ahs3@redhat.com>
#
# Main module for the dsd toolset
#

import tools.env
import tools.env.config
import tools.cmds.cmdline

if __name__ == "__main__":
    tools.env.config.readrc()
    tools.cmds.cmdline.get()
    tools.cmds.cmdline.run()
